# Generated by Django 5.0.3 on 2024-03-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('march_10_app', '0002_product_user_name_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
