# Generated by Django 4.2.7 on 2023-11-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
                ('category', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
